# Copyright (C) 2026 Embedded Artists AB
#
# SPDX-License-Identifier: GPL-2.0+
#

ifdef CONFIG_SPL_BUILD
obj-y	:= ../../renesas/rcar-common/gen3-spl.o
else
obj-y	:= rzg3l-ea-som.o ../../renesas/rcar-common/common.o
endif
